### ISSUE TITLE
A crucial link in the wiki doesn't work

### ISSUE THREAD

**Issue by grdw** [colibri-software/locomotive_plugins#1]
On the wiki page I read: "To install the plugin in LocomotiveCMS, simply create a LocomotiveCMS app and add your plugin gem to the app's Gemfile in the locomotive_plugins group."

The problem is that the URL "create a LocomotiveCMS app" return a 404. I would like to know how to create an app because that's where the creation of my plugin goes wrong.

Also see: http://stackoverflow.com/questions/17367518/how-to-setup-a-basic-locomotive-cms-plugin

**Comment by greeneca** [comment]
I have updated the Readme. It now points to the correct location. doc.locomotivecms.com is a good site to get any information you need about locomotive.

**Comment by grdw** [comment]
Thank you ;)

2013/7/1 greeneca notifications@github.com

> I have updated the Readme. It now points to the correct location.
> doc.locomotivecms.com is a good site to get any information you need
> about locomotive.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/colibri-software/locomotive_plugins/issues/1#issuecomment-20311581
> .

## 

Gerard Westerhof
