### ISSUE TITLE
Is ruby 1.9 absolutely necessary?

### ISSUE THREAD

**Issue by yourtallness** [colibri-software/locomotive_plugins#3]
Hello,

This gem restricts ruby version to 1.9.
I am currently developing a rails 3.2 / ruby 2 locomotive_cms app...
Is 1.9 an absolute necessity?

Thank you,

Mark

**Comment by greeneca** [comment]
Im not sure. We have not tried running any of it on 2 yet. You could just try forking and removing the dependency.

**Comment by nonfungibletunji** [comment]
i was wondering the same thing, i will fork the gem now and test, report the findings

**Comment by nonfungibletunji** [comment]
debugger gem doesn't work with Ruby 2.1+, so the ruby version needs to stay under 1.9? I am searching for a way to upgrade the locomotive engine to use byebug

**Comment by greeneca** [comment]
To the best of my knowledge the main thing holding back the ruby version
was mongoid. That was a while ago. If the main version is still reliant on
1.9 then it is probably just because he is waiting until the next release
is ready. If you want to try it just fork and upgrade and see what happens.

**Comment by nonfungibletunji** [comment]
I got it working but I needed to take out the dependency of locomotive_plugins gem, inside of the plugins branch of Charlie's engine. I added my forked version of the locomotive_plugins without the rails 1.9 dependency to the gem file of my forked plugins branch. I have everything running local and on heroku!

S. Tunji Turner
sightuary :: @sightuary

**Comment by greeneca** [comment]
There were no other changes just the removal of the 1.9 dependency? If so I
will remove it.

**Comment by nonfungibletunji** [comment]
No other changes.

S. Tunji Turner
sightuary :: @sightuary
